apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - name: synergychat-crawler-1
        image: bootdotdev/synergychat-crawler:latest
        ports:
        - containerPort: 8080
        env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
        volumeMounts:
        - mountPath: /cache
          name: cache-volume

      - name: synergychat-crawler-2
        image: bootdotdev/synergychat-crawler:latest
        ports:
        - containerPort: 8081
        env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_2
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
        volumeMounts:
        - mountPath: /cache
          name: cache-volume

      - name: synergychat-crawler-3
        image: bootdotdev/synergychat-crawler:latest
        ports:
        - containerPort: 8082
        env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_3
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
        volumeMounts:
        - mountPath: /cache
          name: cache-volume

      volumes:
      - name: cache-volume
        emptyDir: {}
